oauth:
  kakao:
    client-id: ${KAKAO_USER_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-url: ${KAKAO_REDIRECT_URL}
  naver:
    secret: ${NAVER_CLIENT_SECRET}
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
      redirect-url: ${NAVER_REDIRECT_URL}