oauth:
  kakao:
    client-id: ${KAKAO_USER_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-url: ${KAKAO_REDIRECT_URL}
  naver:
    secret: ${NAVER_CLIENT_SECRET}
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
      redirect-url: ${NAVER_REDIRECT_URL}

jwt:
  secret: ${secretKey}

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true